In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('data/crime_csv_all_years.csv')

In [3]:
df.dropna(inplace=True)
#remove missing data, all (or nearly all) of which is the non-property crime data

In [4]:
df.rename(index=str, columns={"YEAR": "year", "MONTH": "month", "DAY":"day","HOUR":"hour", "MINUTE":"minute", "NEIGHBOURHOOD":"neighbourhood"},inplace=True)
#rename columns as all caps is annoying

In [5]:
df.head()

,TYPE,year,month,day,hour,minute,HUNDRED_BLOCK,neighbourhood,X,Y
0,Theft from Vehicle,2003,11,23,0.0,1.0,13XX W GEORGIA ST,Central Business District,490745.08,5459529.81
1,Theft from Vehicle,2003,5,9,18.0,0.0,30XX W 8TH AVE,Kitsilano,487465.51,5456929.11
4,Break and Enter Commercial,2003,2,7,0.0,30.0,71XX VICTORIA DR,Victoria-Fraserview,495196.35,5451832.55
5,Break and Enter Commercial,2003,6,2,3.0,4.0,71XX VICTORIA DR,Victoria-Fraserview,495196.35,5451832.55
6,Mischief,2003,12,31,8.0,40.0,10XX W GEORGIA ST,West End,491128.32,5459137.86

In [6]:
df.sort_values(['year','month','day','hour','minute'],inplace=True)
#sort by date

In [7]:
df.head(20)

,TYPE,year,month,day,hour,minute,HUNDRED_BLOCK,neighbourhood,X,Y
2148,Theft from Vehicle,2003,1,1,0.0,0.0,2XX DRAKE ST,Central Business District,490968.94,5457901.26
3215,Theft of Bicycle,2003,1,1,0.0,0.0,6X KEEFER PL,Central Business District,492231.06,5458545.72
7453,Theft from Vehicle,2003,1,1,0.0,0.0,24XX W 1ST AVE,Kitsilano,488324.36,5457580.13
18527,Mischief,2003,1,1,0.0,0.0,17XX PARKER ST,Grandview-Woodland,494981.08,5458118.12
32204,Theft from Vehicle,2003,1,1,0.0,0.0,11XX HOWE ST,Central Business District,490849.97,5458442.50
34232,Theft from Vehicle,2003,1,1,0.0,0.0,57XX CULLODEN ST,Sunset,494285.25,5453254.66
34819,Theft from Vehicle,2003,1,1,0.0,0.0,10XX W 26TH AVE,Shaughnessy,490707.25,5455045.50
45038,Break and Enter Residential/Other,2003,1,1,0.0,0.0,9XX W 15TH AVE,Fairview,490791.12,5456127.88
48249,Break and Enter Commercial,2003,1,1,0.0,0.0,64XX VICTORIA DR,Victoria-Fraserview,495220.95,5452631.14
48331,Theft from Vehicle,2003,1,1,0.0,0.0,33XX ROSEMONT DR,Killarney,497388.60,5451449.73
48386,Theft of Bicycle,2003,1,1,0.0,0.0,30XX W 4TH AVE,Kitsilano,487421.31,5457307.47
5783,Theft from Vehicle,2003,1,1,0.0,1.0,26XX E 48TH AVE,Victoria-Fraserview,496028.76,5452569.01
7935,Break and Enter Residential/Other,2003,1,1,0.0,1.0,34XX W 42ND AVE,Dunbar-Southlands,486837.11,5453468.15
36817,Theft of Bicycle,2003,1,1,0.0,5.0,11XX HORNBY ST,Central Business District,490705.34,5458446.09
9491,Vehicle Collision or Pedestrian Struck (with I...,2003,1,1,0.0,19.0,NELSON ST / THURLOW ST,West End,490687.00,5458867.00
28294,Break and Enter Residential/Other,2003,1,1,0.0,20.0,19XX PARKER ST,Grandview-Woodland,495279.46,5458105.92
12387,Mischief,2003,1,1,0.0,30.0,15XX W 66TH AVE,Marpole,489683.62,5450960.73
19542,Mischief,2003,1,1,0.0,30.0,9XX CANADA PL,Central Business District,491613.02,5459490.77
38679,Theft from Vehicle,2003,1,1,0.0,30.0,4XX ABBOTT ST,Central Business District,492183.96,5458755.30
25321,Theft from Vehicle,2003,1,1,1.0,0.0,13XX SW MARINE DR,Marpole,490174.85,5450028.53

In [8]:
df['TYPE'].unique()
#perhaps remove the vehicle entries before removing type

array(['Theft from Vehicle', 'Theft of Bicycle', 'Mischief',
       'Break and Enter Residential/Other', 'Break and Enter Commercial',
       'Vehicle Collision or Pedestrian Struck (with Injury)',
       'Theft of Vehicle', 'Other Theft',
       'Vehicle Collision or Pedestrian Struck (with Fatality)'], dtype=object)

In [9]:
df.drop(['minute', 'HUNDRED_BLOCK','TYPE'], axis=1,inplace=True)
#remove extraneous data

In [10]:
df.apply(pd.to_numeric, errors='ignore')

,year,month,day,hour,neighbourhood,X,Y
2148,2003,1,1,0.0,Central Business District,490968.94,5457901.26
3215,2003,1,1,0.0,Central Business District,492231.06,5458545.72
7453,2003,1,1,0.0,Kitsilano,488324.36,5457580.13
18527,2003,1,1,0.0,Grandview-Woodland,494981.08,5458118.12
32204,2003,1,1,0.0,Central Business District,490849.97,5458442.50
34232,2003,1,1,0.0,Sunset,494285.25,5453254.66
34819,2003,1,1,0.0,Shaughnessy,490707.25,5455045.50
45038,2003,1,1,0.0,Fairview,490791.12,5456127.88
48249,2003,1,1,0.0,Victoria-Fraserview,495220.95,5452631.14
48331,2003,1,1,0.0,Killarney,497388.60,5451449.73
48386,2003,1,1,0.0,Kitsilano,487421.31,5457307.47
5783,2003,1,1,0.0,Victoria-Fraserview,496028.76,5452569.01
7935,2003,1,1,0.0,Dunbar-Southlands,486837.11,5453468.15
36817,2003,1,1,0.0,Central Business District,490705.34,5458446.09
9491,2003,1,1,0.0,West End,490687.00,5458867.00
28294,2003,1,1,0.0,Grandview-Woodland,495279.46,5458105.92
12387,2003,1,1,0.0,Marpole,489683.62,5450960.73
19542,2003,1,1,0.0,Central Business District,491613.02,5459490.77
38679,2003,1,1,0.0,Central Business District,492183.96,5458755.30
25321,2003,1,1,1.0,Marpole,490174.85,5450028.53
37664,2003,1,1,1.0,Central Business District,491084.84,5458236.56
7887,2003,1,1,1.0,Hastings-Sunrise,495898.84,5459438.82
30338,2003,1,1,1.0,West End,490830.09,5459359.47
20978,2003,1,1,1.0,Grandview-Woodland,495107.25,5459083.57
34610,2003,1,1,1.0,Kitsilano,488772.00,5457479.02
17137,2003,1,1,1.0,Riley Park,492627.84,5454543.55
21022,2003,1,1,1.0,Riley Park,492627.84,5454543.55
12711,2003,1,1,2.0,Central Business District,491424.48,5458592.56
20710,2003,1,1,2.0,Grandview-Woodland,495086.32,5457705.34
25439,2003,1,1,2.0,Marpole,490135.31,5450044.63
...,...,...,...,...,...,...,...
560014,2018,4,19,9.0,Kerrisdale,489450.74,5453147.77
553985,2018,4,19,10.0,Arbutus Ridge,487810.51,5455374.62
553349,2018,4,19,11.0,Riley Park,492622.87,5454382.49
551453,2018,4,19,12.0,Marpole,492133.88,5451085.44
555392,2018,4,19,12.0,Central Business District,491117.43,5458996.15
553150,2018,4,19,12.0,Killarney,497805.83,5453242.00
556050,2018,4,19,13.0,Kitsilano,487757.88,5457304.72
551789,2018,4,19,13.0,West End,491151.77,5459036.23
551047,2018,4,19,13.0,Sunset,493939.05,5451801.93
555159,2018,4,19,13.0,Central Business District,491359.53,5458663.12
560429,2018,4,19,13.0,Killarney,498101.15,5452074.24
555492,2018,4,19,14.0,Central Business District,491720.70,5459179.65
560450,2018,4,19,14.0,Kensington-Cedar Cottage,494922.84,5456615.84
554623,2018,4,19,15.0,Central Business District,491369.94,5458247.75
558609,2018,4,19,15.0,Grandview-Woodland,495371.00,5458717.00
555295,2018,4,19,15.0,Central Business District,491117.43,5458996.15
555521,2018,4,19,15.0,Marpole,489762.86,5450783.83
556308,2018,4,19,16.0,Shaughnessy,489697.66,5455569.44
557762,2018,4,19,16.0,Grandview-Woodland,494999.85,5456623.73
557612,2018,4,19,17.0,Strathcona,493650.59,5457558.72
557359,2018,4,19,17.0,Mount Pleasant,492936.76,5456669.24
551190,2018,4,19,18.0,Central Business District,491566.37,5458460.38
555614,2018,4,19,18.0,Mount Pleasant,491657.21,5456952.73
554476,2018,4,19,19.0,Oakridge,490664.92,5452750.53
558919,2018,4,19,19.0,Central Business District,491886.00,5458643.00
553021,2018,4,19,19.0,Kitsilano,489234.74,5457264.32
556514,2018,4,19,20.0,Strathcona,493071.47,5458931.50
550752,2018,4,19,20.0,Central Business District,492749.16,5458835.08
554165,2018,4,19,20.0,Central Business District,491083.06,5458397.69
558908,2018,4,19,22.0,Central Business District,492175.41,5459048.55

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 501528 entries, 2148 to 558908
Data columns (total 7 columns):
year             501528 non-null int64
month            501528 non-null int64
day              501528 non-null int64
hour             501528 non-null float64
neighbourhood    501528 non-null object
X                501528 non-null float64
Y                501528 non-null float64
dtypes: float64(3), int64(3), object(1)
memory usage: 30.6+ MB

In [12]:
#bin by 12am-8am, 8am-4pm, 4pm -12am

In [13]:
hourbins = [-0.1,8.0,16.0,24.1]
hourlabels = ['1200am-0759am', '0800am-0359pm', '0400pm-1159pm']
df['day_segment'] = pd.cut(df["hour"], bins=hourbins,labels=hourlabels)

#df['day_segment'] = pd.cut(df['hour'], [0, 8, 16,24], labels=['1200am-0759am', '0800am-0359pm', '0400pm-1159pm'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 501528 entries, 2148 to 558908
Data columns (total 8 columns):
year             501528 non-null int64
month            501528 non-null int64
day              501528 non-null int64
hour             501528 non-null float64
neighbourhood    501528 non-null object
X                501528 non-null float64
Y                501528 non-null float64
day_segment      501528 non-null category
dtypes: category(1), float64(3), int64(3), object(1)
memory usage: 31.1+ MB

In [15]:
df.head(100)

,year,month,day,hour,neighbourhood,X,Y,day_segment
2148,2003,1,1,0.0,Central Business District,490968.94,5457901.26,1200am-0759am
3215,2003,1,1,0.0,Central Business District,492231.06,5458545.72,1200am-0759am
7453,2003,1,1,0.0,Kitsilano,488324.36,5457580.13,1200am-0759am
18527,2003,1,1,0.0,Grandview-Woodland,494981.08,5458118.12,1200am-0759am
32204,2003,1,1,0.0,Central Business District,490849.97,5458442.50,1200am-0759am
34232,2003,1,1,0.0,Sunset,494285.25,5453254.66,1200am-0759am
34819,2003,1,1,0.0,Shaughnessy,490707.25,5455045.50,1200am-0759am
45038,2003,1,1,0.0,Fairview,490791.12,5456127.88,1200am-0759am
48249,2003,1,1,0.0,Victoria-Fraserview,495220.95,5452631.14,1200am-0759am
48331,2003,1,1,0.0,Killarney,497388.60,5451449.73,1200am-0759am
48386,2003,1,1,0.0,Kitsilano,487421.31,5457307.47,1200am-0759am
5783,2003,1,1,0.0,Victoria-Fraserview,496028.76,5452569.01,1200am-0759am
7935,2003,1,1,0.0,Dunbar-Southlands,486837.11,5453468.15,1200am-0759am
36817,2003,1,1,0.0,Central Business District,490705.34,5458446.09,1200am-0759am
9491,2003,1,1,0.0,West End,490687.00,5458867.00,1200am-0759am
28294,2003,1,1,0.0,Grandview-Woodland,495279.46,5458105.92,1200am-0759am
12387,2003,1,1,0.0,Marpole,489683.62,5450960.73,1200am-0759am
19542,2003,1,1,0.0,Central Business District,491613.02,5459490.77,1200am-0759am
38679,2003,1,1,0.0,Central Business District,492183.96,5458755.30,1200am-0759am
25321,2003,1,1,1.0,Marpole,490174.85,5450028.53,1200am-0759am
37664,2003,1,1,1.0,Central Business District,491084.84,5458236.56,1200am-0759am
7887,2003,1,1,1.0,Hastings-Sunrise,495898.84,5459438.82,1200am-0759am
30338,2003,1,1,1.0,West End,490830.09,5459359.47,1200am-0759am
20978,2003,1,1,1.0,Grandview-Woodland,495107.25,5459083.57,1200am-0759am
34610,2003,1,1,1.0,Kitsilano,488772.00,5457479.02,1200am-0759am
17137,2003,1,1,1.0,Riley Park,492627.84,5454543.55,1200am-0759am
21022,2003,1,1,1.0,Riley Park,492627.84,5454543.55,1200am-0759am
12711,2003,1,1,2.0,Central Business District,491424.48,5458592.56,1200am-0759am
20710,2003,1,1,2.0,Grandview-Woodland,495086.32,5457705.34,1200am-0759am
25439,2003,1,1,2.0,Marpole,490135.31,5450044.63,1200am-0759am
...,...,...,...,...,...,...,...,...
14789,2003,1,1,11.0,Mount Pleasant,492527.39,5456495.51,0800am-0359pm
1085,2003,1,1,12.0,Central Business District,492005.87,5458173.62,0800am-0359pm
7662,2003,1,1,12.0,South Cambie,490761.31,5453477.54,0800am-0359pm
13971,2003,1,1,12.0,Central Business District,492577.88,5458943.30,0800am-0359pm
15273,2003,1,1,12.0,Arbutus Ridge,488613.83,5455222.39,0800am-0359pm
27475,2003,1,1,12.0,West End,490786.46,5459476.01,0800am-0359pm
31426,2003,1,1,12.0,West End,490400.79,5458840.38,0800am-0359pm
43482,2003,1,1,12.0,Central Business District,492073.89,5459075.98,0800am-0359pm
45988,2003,1,1,12.0,Central Business District,492024.04,5458628.81,0800am-0359pm
46452,2003,1,1,12.0,Central Business District,492194.48,5459043.46,0800am-0359pm
47296,2003,1,1,12.0,Hastings-Sunrise,496826.08,5457397.96,0800am-0359pm
49077,2003,1,1,12.0,South Cambie,491399.11,5456000.37,0800am-0359pm
14739,2003,1,1,12.0,West End,490270.91,5459603.25,0800am-0359pm
35125,2003,1,1,12.0,Renfrew-Collingwood,497676.19,5456231.22,0800am-0359pm
28484,2003,1,1,13.0,Central Business District,490919.39,5458083.13,0800am-0359pm
558,2003,1,1,13.0,Strathcona,493591.23,5458009.62,0800am-0359pm
11355,2003,1,1,13.0,Grandview-Woodland,494922.38,5456975.18,0800am-0359pm
33718,2003,1,1,13.0,Grandview-Woodland,494922.38,5456975.18,0800am-0359pm
20901,2003,1,1,13.0,Kitsilano,488550.90,5457475.22,0800am-0359pm
27474,2003,1,1,13.0,West End,490786.46,5459476.01,0800am-0359pm
37337,2003,1,1,14.0,Central Business District,490730.37,5458609.87,0800am-0359pm
891,2003,1,1,14.0,Riley Park,491926.69,5455899.50,0800am-0359pm
3594,2003,1,1,14.0,Kensington-Cedar Cottage,494917.83,5456315.97,0800am-0359pm
16608,2003,1,1,14.0,Kensington-Cedar Cottage,494917.83,5456315.97,0800am-0359pm
20397,2003,1,1,15.0,Central Business District,491171.99,5458918.15,0800am-0359pm
33741,2003,1,1,15.0,South Cambie,490945.95,5455836.23,0800am-0359pm
5893,2003,1,1,15.0,Central Business District,492575.63,5458228.80,0800am-0359pm
1544,2003,1,1,15.0,Killarney,496782.22,5450445.75,0800am-0359pm
14792,2003,1,1,15.0,Mount Pleasant,492509.34,5456486.76,0800am-0359pm
24392,2003,1,1,15.0,Central Business District,491609.07,5458916.05,0800am-0359pm

In [16]:
df_temp=df[['year', 'month', 'day', 'day_segment', 'neighbourhood']]
#group by neighborhood, by day_segment, with a count

In [17]:
df_temp.head()

       year  month  day    day_segment              neighbourhood
2148   2003      1    1  1200am-0759am  Central Business District
3215   2003      1    1  1200am-0759am  Central Business District
7453   2003      1    1  1200am-0759am                  Kitsilano
18527  2003      1    1  1200am-0759am         Grandview-Woodland
32204  2003      1    1  1200am-0759am  Central Business District

In [18]:
df_temp2=df_temp.groupby(df_temp.columns.tolist()).size()

In [19]:
df_temp2.head(20)

year  month  day  day_segment    neighbourhood
2003  1      1    1200am-0759am  Central Business District    14
                                 Dunbar-Southlands             1
                                 Fairview                      1
                                 Grandview-Woodland            6
                                 Hastings-Sunrise              3
                                 Kensington-Cedar Cottage      3
                                 Kerrisdale                    1
                                 Killarney                     1
                                 Kitsilano                     3
                                 Marpole                       3
                                 Mount Pleasant                3
                                 Renfrew-Collingwood           3
                                 Riley Park                    2
                                 Shaughnessy                   1
                                 Strathcona                    2
                                 Sunset                        2
                                 Victoria-Fraserview           5
                                 West End                      4
                  0800am-0359pm  Arbutus Ridge                 1
                                 Central Business District    13
dtype: int64

In [20]:
df_temp2[0]

14

In [21]:
df_new=pd.DataFrame(df_temp2).reset_index()

In [22]:
df_new.rename(index=str, columns={ 0 :"number_of_crimes"},inplace=True)

In [23]:
df_new.head()

,year,month,day,day_segment,neighbourhood,number_of_crimes
0,2003,1,1,1200am-0759am,Central Business District,14
1,2003,1,1,1200am-0759am,Dunbar-Southlands,1
2,2003,1,1,1200am-0759am,Fairview,1
3,2003,1,1,1200am-0759am,Grandview-Woodland,6
4,2003,1,1,1200am-0759am,Hastings-Sunrise,3

In [24]:
wdf=pd.read_csv('data/Blaine.csv')

In [25]:
wdf.head()

,STATION,NAME,DATE,MDPR,PRCP,SNOW,SNWD,TMAX,TMIN,TOBS,WT01
0,USC00450729,"BLAINE, WA US",2003-01-01,NaN,0.43,0.0,0.0,45.0,38.0,39.0,NaN
1,USC00450729,"BLAINE, WA US",2003-01-02,NaN,0.87,0.0,0.0,54.0,39.0,54.0,NaN
2,USC00450729,"BLAINE, WA US",2003-01-03,NaN,0.33,0.0,0.0,54.0,40.0,47.0,NaN
3,USC00450729,"BLAINE, WA US",2003-01-04,NaN,0.77,0.0,0.0,53.0,43.0,51.0,NaN
4,USC00450729,"BLAINE, WA US",2003-01-05,NaN,0.00,0.0,0.0,52.0,37.0,47.0,NaN

In [26]:
wdf=wdf[['DATE','PRCP','TMAX','TMIN']]
wdf.rename(index=str, columns={ "PRCP": "prcp", "TMAX":"tmax","TMIN":"tmin"},inplace=True)

In [27]:
wdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4718 entries, 0 to 4717
Data columns (total 4 columns):
DATE    4718 non-null object
prcp    4684 non-null float64
tmax    4675 non-null float64
tmin    4673 non-null float64
dtypes: float64(3), object(1)
memory usage: 184.3+ KB

In [28]:
wdf.interpolate(inplace=True)

In [29]:
wdf.isnull().sum()

DATE    0
prcp    0
tmax    0
tmin    0
dtype: int64

In [30]:
wdf['year'] = wdf.DATE.str.split('-').str.get(0)
wdf['month'] = wdf.DATE.str.split('-').str.get(1) 
wdf['day'] = wdf.DATE.str.split('-').str.get(2) 
wdf.drop('DATE', axis=1,inplace=True)

In [31]:
wdf.head()

   prcp  tmax  tmin  year month day
0  0.43  45.0  38.0  2003    01  01
1  0.87  54.0  39.0  2003    01  02
2  0.33  54.0  40.0  2003    01  03
3  0.77  53.0  43.0  2003    01  04
4  0.00  52.0  37.0  2003    01  05

In [32]:
wdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4718 entries, 0 to 4717
Data columns (total 6 columns):
prcp     4718 non-null float64
tmax     4718 non-null float64
tmin     4718 non-null float64
year     4718 non-null object
month    4718 non-null object
day      4718 non-null object
dtypes: float64(3), object(3)
memory usage: 258.0+ KB

In [33]:
wdf=wdf.apply(pd.to_numeric, errors='ignore')

In [34]:
wdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4718 entries, 0 to 4717
Data columns (total 6 columns):
prcp     4718 non-null float64
tmax     4718 non-null float64
tmin     4718 non-null float64
year     4718 non-null int64
month    4718 non-null int64
day      4718 non-null int64
dtypes: float64(3), int64(3)
memory usage: 258.0+ KB

In [35]:
new_df1=pd.merge(df_new,wdf, how='inner', on=['year','month','day'])

In [36]:
new_df1.head(200)

,year,month,day,day_segment,neighbourhood,number_of_crimes,prcp,tmax,tmin
0,2003,1,1,1200am-0759am,Central Business District,14,0.43,45.0,38.0
1,2003,1,1,1200am-0759am,Dunbar-Southlands,1,0.43,45.0,38.0
2,2003,1,1,1200am-0759am,Fairview,1,0.43,45.0,38.0
3,2003,1,1,1200am-0759am,Grandview-Woodland,6,0.43,45.0,38.0
4,2003,1,1,1200am-0759am,Hastings-Sunrise,3,0.43,45.0,38.0
5,2003,1,1,1200am-0759am,Kensington-Cedar Cottage,3,0.43,45.0,38.0
6,2003,1,1,1200am-0759am,Kerrisdale,1,0.43,45.0,38.0
7,2003,1,1,1200am-0759am,Killarney,1,0.43,45.0,38.0
8,2003,1,1,1200am-0759am,Kitsilano,3,0.43,45.0,38.0
9,2003,1,1,1200am-0759am,Marpole,3,0.43,45.0,38.0
10,2003,1,1,1200am-0759am,Mount Pleasant,3,0.43,45.0,38.0
11,2003,1,1,1200am-0759am,Renfrew-Collingwood,3,0.43,45.0,38.0
12,2003,1,1,1200am-0759am,Riley Park,2,0.43,45.0,38.0
13,2003,1,1,1200am-0759am,Shaughnessy,1,0.43,45.0,38.0
14,2003,1,1,1200am-0759am,Strathcona,2,0.43,45.0,38.0
15,2003,1,1,1200am-0759am,Sunset,2,0.43,45.0,38.0
16,2003,1,1,1200am-0759am,Victoria-Fraserview,5,0.43,45.0,38.0
17,2003,1,1,1200am-0759am,West End,4,0.43,45.0,38.0
18,2003,1,1,0800am-0359pm,Arbutus Ridge,1,0.43,45.0,38.0
19,2003,1,1,0800am-0359pm,Central Business District,13,0.43,45.0,38.0
20,2003,1,1,0800am-0359pm,Grandview-Woodland,4,0.43,45.0,38.0
21,2003,1,1,0800am-0359pm,Hastings-Sunrise,1,0.43,45.0,38.0
22,2003,1,1,0800am-0359pm,Kensington-Cedar Cottage,4,0.43,45.0,38.0
23,2003,1,1,0800am-0359pm,Killarney,1,0.43,45.0,38.0
24,2003,1,1,0800am-0359pm,Kitsilano,1,0.43,45.0,38.0
25,2003,1,1,0800am-0359pm,Mount Pleasant,5,0.43,45.0,38.0
26,2003,1,1,0800am-0359pm,Renfrew-Collingwood,3,0.43,45.0,38.0
27,2003,1,1,0800am-0359pm,Riley Park,4,0.43,45.0,38.0
28,2003,1,1,0800am-0359pm,South Cambie,4,0.43,45.0,38.0
29,2003,1,1,0800am-0359pm,Strathcona,2,0.43,45.0,38.0
...,...,...,...,...,...,...,...,...,...
170,2003,1,4,0400pm-1159pm,Kensington-Cedar Cottage,2,0.77,53.0,43.0
171,2003,1,4,0400pm-1159pm,Killarney,1,0.77,53.0,43.0
172,2003,1,4,0400pm-1159pm,Kitsilano,8,0.77,53.0,43.0
173,2003,1,4,0400pm-1159pm,Marpole,6,0.77,53.0,43.0
174,2003,1,4,0400pm-1159pm,Mount Pleasant,2,0.77,53.0,43.0
175,2003,1,4,0400pm-1159pm,Renfrew-Collingwood,4,0.77,53.0,43.0
176,2003,1,4,0400pm-1159pm,Riley Park,3,0.77,53.0,43.0
177,2003,1,4,0400pm-1159pm,Shaughnessy,1,0.77,53.0,43.0
178,2003,1,4,0400pm-1159pm,Strathcona,4,0.77,53.0,43.0
179,2003,1,4,0400pm-1159pm,Sunset,1,0.77,53.0,43.0
180,2003,1,4,0400pm-1159pm,Victoria-Fraserview,1,0.77,53.0,43.0
181,2003,1,4,0400pm-1159pm,West End,12,0.77,53.0,43.0
182,2003,1,4,0400pm-1159pm,West Point Grey,1,0.77,53.0,43.0
183,2003,1,5,1200am-0759am,Central Business District,14,0.00,52.0,37.0
184,2003,1,5,1200am-0759am,Fairview,6,0.00,52.0,37.0
185,2003,1,5,1200am-0759am,Grandview-Woodland,1,0.00,52.0,37.0
186,2003,1,5,1200am-0759am,Hastings-Sunrise,2,0.00,52.0,37.0
187,2003,1,5,1200am-0759am,Kitsilano,4,0.00,52.0,37.0
188,2003,1,5,1200am-0759am,Mount Pleasant,2,0.00,52.0,37.0
189,2003,1,5,1200am-0759am,Renfrew-Collingwood,3,0.00,52.0,37.0
190,2003,1,5,1200am-0759am,South Cambie,1,0.00,52.0,37.0
191,2003,1,5,1200am-0759am,Victoria-Fraserview,1,0.00,52.0,37.0
192,2003,1,5,1200am-0759am,West End,5,0.00,52.0,37.0
193,2003,1,5,1200am-0759am,West Point Grey,1,0.00,52.0,37.0
194,2003,1,5,0800am-0359pm,Arbutus Ridge,1,0.00,52.0,37.0
195,2003,1,5,0800am-0359pm,Central Business District,8,0.00,52.0,37.0
196,2003,1,5,0800am-0359pm,Fairview,1,0.00,52.0,37.0
197,2003,1,5,0800am-0359pm,Hastings-Sunrise,1,0.00,52.0,37.0
198,2003,1,5,0800am-0359pm,Kitsilano,2,0.00,52.0,37.0
199,2003,1,5,0800am-0359pm,Oakridge,2,0.00,52.0,37.0